### ISSUE TITLE
Distributed training is the only way to go.

### ISSUE THREAD

**Issue by xuboot** [CrystalNeuro/visual-concept-translator#8]
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/usr/local/data/miniconda3/envs/vct/lib/python3.8/site-packages/accelerate/accelerator.py:321: UserWarning: `log_with=tensorboard` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
08/28/2023 13:59:19 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda
Mixed precision type: no

Traceback (most recent call last):
  File "main.py", line 829, in <module>
    args = multi_concept_inversion()
  File "main.py", line 551, in multi_concept_inversion
    tokenizer = MultiTokenCLIPTokenizer.from_pretrained(args.pretrained_model_name_or_path, subfolder="tokenizer")
  File "/usr/local/data/miniconda3/envs/vct/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1763, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "/usr/local/data/miniconda3/envs/vct/lib/python3.8/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/usr/local/data/miniconda3/envs/vct/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/data/miniconda3/envs/vct/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/put/your/downloaded/huggingface/model'. Use `repo_type` argument if needed.
Traceback (most recent call last):
  File "/usr/local/data/miniconda3/envs/vct/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/data/miniconda3/envs/vct/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/data/miniconda3/envs/vct/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/data/miniconda3/envs/vct/lib/python3.8/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/local/data/miniconda3/envs/vct/bin/python', 'main.py', '--concept_image_dir=./examples/concept_image', '--content_image_dir=./examples/content_image', '--pretrained_model_name_or_path=/put/your/downloaded/huggingface/model', '--output_image_path=./outputs', '--initializer_token=girl', '--max_train_steps=50', '--concept_embedding_num=3', '--cross_attention_injection_ratio=0.2', '--self_attention_injection_ratio=0.9', '--use_l1']' returned non-zero exit status 1.

**Comment by CrystalNeuro** [comment]
I think this error is caused by the absence of the "pretrained_model_name_or_path" argument.

**Comment by gustn9609** [comment]
@xuboot Did you solve this problem? I have the same error.
