### ISSUE TITLE
accelerate launch main.py     --concept_image_dir="./examples/concept_image"     --content_image_dir="./examples/content_image"     --output_image_path="./outputs"     --initializer_token="girl"     --max_train_steps=3     --concept_embedding_num=3     --cross_attention_injection_ratio=0.2     --self_attention_injection_ratio=0.9     --use_l1

### ISSUE THREAD

**Issue by xuboot** [CrystalNeuro/visual-concept-translator#9]
{'prediction_type'} was not found in config. Values will be initialized to default values.
{'dual_cross_attention', 'only_cross_attention', 'use_linear_projection', 'upcast_attention', 'num_class_embeds'} was not found in config. Values will be initialized to default values.
/usr/local/data/miniconda3/envs/vct/lib/python3.8/site-packages/diffusers/configuration_utils.py:195: FutureWarning: It is deprecated to pass a pretrained model name or path to `from_config`.If you were trying to load a scheduler, please use <class 'diffusers.schedulers.scheduling_ddim.DDIMScheduler'>.from_pretrained(...) instead. Otherwise, please make sure to pass a configuration dictionary instead. This functionality will be removed in v1.0.0.
  deprecate("config-passed-as-path", "1.0.0", deprecation_message, standard_warn=False)
Traceback (most recent call last):
  File "/usr/local/data/miniconda3/envs/vct/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 326, in load_config
    config_file = hf_hub_download(
  File "/usr/local/data/miniconda3/envs/vct/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/data/miniconda3/envs/vct/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'runwayml/stable-diffusion-v1-5/scheduler'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 830, in <module>
    pivot_turning_inversion.inversion(args.output_dir, args.content_image_dir, args.output_image_path, args.concept_image_dir, args.max_train_steps, args.cross_attention_injection_ratio, args.self_attention_injection_ratio, args.pretrained_model_name_or_path)
  File "/root/visual-concept-translator/pivot_turning_inversion.py", line 216, in inversion
    main(model_id, input_img_path, step_list, prompt_name_backward, forward_prompt, backward_prompts, out_img_save_path, content_name_prefix, cross_attention_injection_ratio, self_attention_injection_ratio, pretrained_model_name_or_path)
  File "/root/visual-concept-translator/pivot_turning_inversion.py", line 91, in main
    pipe.scheduler = DDIMScheduler.from_config(os.path.join(pretrained_model_name_or_path, "scheduler"))
  File "/usr/local/data/miniconda3/envs/vct/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 196, in from_config
    config, kwargs = cls.load_config(pretrained_model_name_or_path=config, return_unused_kwargs=True, **kwargs)
  File "/usr/local/data/miniconda3/envs/vct/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 363, in load_config
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like runwayml/stable-diffusion-v1-5/scheduler is not the path to a directory containing a scheduler_config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
Traceback (most recent call last):
  File "/usr/local/data/miniconda3/envs/vct/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/data/miniconda3/envs/vct/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/data/miniconda3/envs/vct/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/data/miniconda3/envs/vct/lib/python3.8/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/local/data/miniconda3/envs/vct/bin/python', 'main.py', '--concept_image_dir=./examples/concept_image', '--content_image_dir=./examples/content_image', '--output_image_path=./outputs', '--initializer_token=girl', '--max_train_steps=3', '--concept_embedding_num=3', '--cross_attention_injection_ratio=0.2', '--self_attention_injection_ratio=0.9', '--use_l1']' returned non-zero exit status 1.

**Comment by CrystalNeuro** [comment]
This loading error is caused by the use of the online huggingface model. You can download the pre-trained model locally and put that path to "pretrained_model_name_or_path" argument. Again, please make sure your specific path contains subfolders such as tokenizer and text_encoder, just as in the format of the online model.

**Comment by xuboot** [comment]
@CrystalNeuro What are the pre-trained models to download?

**Comment by xuboot** [comment]
@CrystalNeuro I'm new to this, and the github docs aren't specific about which models, so I'm working from the docs

**Comment by xuboot** [comment]
@CrystalNeuro If I download the sd1.5 model to the local server, then he still reports an error OSError: Can't load tokenizer for '/root/visual-concept-translator/model'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/ root/visual-concept-translator/model' is the correct path to a directory containing all relevant files for a MultiTokenCLIPTokenizer tokenizer.
Traceback (most recent call last):, I see "To avoid the loading error or repeated downloads, it is recommended to download the pre-trained huggingface model such as stable-diffusion-v1-5 to local. Then put the downloaded path into pretrained_model_name_or_path." This sentence means This sentence means that the model for sd1.5 is uploaded to the server, it does not specify which model dependencies are downloaded, and there is no corresponding link in the code.

Translated with www.DeepL.com/Translator (free version)

**Comment by JQJQ2021** [comment]
> @CrystalNeuro If I download the sd1.5 model to the local server, then he still reports an error OSError: Can't load tokenizer for '/root/visual-concept-translator/model'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/ root/visual-concept-translator/model' is the correct path to a directory containing all relevant files for a MultiTokenCLIPTokenizer tokenizer. Traceback (most recent call last):, I see "To avoid the loading error or repeated downloads, it is recommended to download the pre-trained huggingface model such as stable-diffusion-v1-5 to local. Then put the downloaded path into pretrained_model_name_or_path." This sentence means This sentence means that the model for sd1.5 is uploaded to the server, it does not specify which model dependencies are downloaded, and there is no corresponding link in the code.
> 
> Translated with [www.DeepL.com/Translator](http://www.DeepL.com/Translator) (free version)

Have you solved this problem? I have the same problem as you.Thanks！

**Comment by cyn-jackal** [comment]
> This loading error is caused by the use of the online huggingface model. You can download the pre-trained model locally and put that path to "pretrained_model_name_or_path" argument. Again, please make sure your specific path contains subfolders such as tokenizer and text_encoder, just as in the format of the online model.

I'm encounter to this problem too. i try to download v1-5-pruned-emaonly.ckpt from hugging face and try to use something like this "--pretrained_model_name_or_path="./model/v1-5-pruned-emaonly.ckpt" but it's look like i'm faceing another issue about subfolder="tokenizer". Because i'm really new here i'm so sorry. What should i do with subfloder name tokenizer? 
![image](https://github.com/CrystalNeuro/visual-concept-translator/assets/52826299/8b7e48b2-9fb6-4503-ab3e-6d28f96e0019)

**Comment by gustn9609** [comment]
@Chayanonjackal Did you solve the problem? I have the same issue.

**Comment by JQJQ2021** [comment]
![1709437013044](https://github.com/CrystalNeuro/visual-concept-translator/assets/87011537/82a97b90-a55c-4144-b9cb-e005b5e03377)
Hello, can you run through this code? I have downloaded the pre-trained model, but I still seem to encounter some problems. Can you help me take a look? Really need your help, thank you very much!@xuboot@gustn9609@Chayanonjackal@CrystalNeuro

**Comment by JQJQ2021** [comment]
![1709437013044](https://github.com/CrystalNeuro/visual-concept-translator/assets/87011537/677e46b2-9b47-4e3c-9dd7-d95093f16ccd)
Hello, can you run through this code? I have downloaded the pre-trained model, but I still seem to encounter some problems. Can you help me take a look? Really need your help, thank you very much!@xuboot @gustn9609 @Chayanonjackal @CrystalNeuro

**Comment by zhang2002forwin** [comment]
> ![1709437013044](https://private-user-images.githubusercontent.com/87011537/309522418-677e46b2-9b47-4e3c-9dd7-d95093f16ccd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDYxOTMsIm5iZiI6MTcxMTcwNTg5MywicGF0aCI6Ii84NzAxMTUzNy8zMDk1MjI0MTgtNjc3ZTQ2YjItOWI0Ny00ZTNjLTlkZDctZDk1MDkzZjE2Y2NkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA5NTEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZWVhOTdmOTI2M2MxOWRlNmNhMThhMzZlZmZmYjIyYmQzNDhlNjEwOGNkMTk1Mzg2ZTE1ZjVjNGQ0ZWZmMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D_6wK4CSsyQTTeN-7pdky58rLKWV9ggwusyi7M8kHfM) Hello, can you run through this code? I have downloaded the pre-trained model, but I still seem to encounter some problems. Can you help me take a look? Really need your help, thank you very much!@xuboot @gustn9609 @Chayanonjackal @CrystalNeuro

解决了吗？ 我刚下载了离线模型，跑起来了

**Comment by YifanLiang-hust** [comment]
What should I do with the following warnings?
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'CLIPTokenizer'.
The class this function is called from is 'MultiTokenCLIPTokenizer'.
I download stable-diffusion v1-5 on Huggingface
